version: "3.8"

services: 
    api:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        image: crudim2
        volumes: 
            - ./:/usr/app
        ports: 
            - 3000:5000
        restart: unless-stopped
        container_name: crudcon2
