#### Development ####

FROM python:3.8-buster

WORKDIR /usr/app

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./app.py .

ENV FLASK_APP app.py
ENV FLASK_ENV development

COPY . .

CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0" ]